# Generated by Django 5.2.6 on 2025-09-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock_quantity',
            new_name='stock_qty',
        ),
    ]
